FROM ubuntu:bionic

LABEL maintainer="mizu-bai <shiragawa4519@outlook.com>"

ARG PROFILE="/etc/profile"

ENV Multiwfnpath="/opt/Multiwfn_bin"
ENV PATH="$Multiwfnpath:$PATH"

RUN set -x; mkdir -p ${Multiwfnpath} \
    && echo "KMP_STACKSIZE=200M" >> ${PROFILE} \
    && echo "ulimit -s unlimited" >> ${PROFILE} \
    && echo "kernel.shmmax=512000000" >> /etc/sysctl.conf

WORKDIR /source 
